"""Deterministic chunking — a faithful port of lib/rag/chunk.ts.

Same text, same chunks, same hashes, always. That property is load-bearing:
the indexer skips re-embedding by comparing content hashes, so a chunker that
drifted would re-embed the whole corpus on every run, and the eval set is
scored against chunk ids, which are only stable if the boundaries are.

The port is byte-for-byte: it replicates JS string semantics, including
UTF-16 code-unit lengths and slicing (JS `.length`/`.slice` operate on code
units, not code points — emoji and other astral characters count double),
and the exact JS whitespace set for the collapse and the trims.
tests/test_chunk.py proves this against golden fixtures generated by the
real TypeScript chunker (tests/fixtures/generate_golden.ts).
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Any

MAX_CHUNK_CHARS = 900
CHUNK_OVERLAP_CHARS = 150

# The ECMAScript whitespace set: WhiteSpace + LineTerminator, including
# U+FEFF. Python's \\s matches a slightly different set (it adds U+001C-1F
# and U+0085, and misses U+FEFF), so we spell the JS set out explicitly.
_JS_WS = " \t\n\v\f\r\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff"
_JS_WS_RE = re.compile("[" + _JS_WS + "]+")


def hash_text(text: str) -> str:
    """SHA-256 of the UTF-8 text, hex. Matches `encode(sha256(convert_to(t,'UTF8')),'hex')` in SQL.

    The edge case mirrors the TS implementation: TextEncoder replaces unpaired
    UTF-16 surrogates with U+FFFD, so we do the same via errors="replace".
    """
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def normalize(text: str) -> str:
    """Collapses runs of whitespace so trailing-space edits do not re-chunk a document."""
    return _JS_WS_RE.sub(" ", text).strip(_JS_WS)


def _to_units(text: str) -> list[str]:
    """Splits a string into UTF-16 code units, mirroring JS string indexing.

    Python strings index by code point, JS by code unit. For texts that are
    entirely BMP the two are identical, but an astral character (emoji,
    CJK ext-B, ...) is one code point and two code units. Lengths and slices
    must count the way the TS chunker counts or boundaries drift.
    """
    if not text:
        return []
    raw = text.encode("utf-16-le", "surrogatepass")
    return [raw[i : i + 2].decode("utf-16-le", "surrogatepass") for i in range(0, len(raw), 2)]


def _from_units(units: list[str]) -> str:
    """Rejoins UTF-16 code units into a Python string.

    Round-tripping through UTF-16 bytes recombines surrogate pairs into the
    original code points, so an emoji that is two units on the way in is one
    code point on the way out. Only a pair actually split by a hard-cut stays
    as a lone surrogate, which is exactly what the JS chunker produces.
    """
    joined = "".join(units)
    return joined.encode("utf-16-le", "surrogatepass").decode("utf-16-le", "surrogatepass")


def _trim_units(units: list[str]) -> list[str]:
    """JS `String.prototype.trim` on a list of code units."""
    start = 0
    end = len(units)
    while start < end and units[start] in _JS_WS:
        start += 1
    while end > start and units[end - 1] in _JS_WS:
        end -= 1
    return units[start:end]


def _sentences(text: str, max_chars: int) -> list[list[str]]:
    """Splits on sentence ends, keeping the terminator with its sentence.

    Scanned rather than matched with a regex, exactly like the TS original: a
    regex silently skips any span it cannot match (a decimal point made the
    word `interest` vanish from the index), while this scan guarantees every
    character lands in exactly one part. A terminator ends a sentence only
    when a space follows it, which keeps decimals and INV-1.2-style
    identifiers intact. A sentence longer than maxChars is hard-cut.

    Parts are returned as UTF-16 code-unit lists so every downstream length
    check counts the way JS does.
    """
    units = _to_units(text)
    out: list[list[str]] = []

    def push(raw: list[str]) -> None:
        part = _trim_units(raw)
        if not part:
            return
        if len(part) <= max_chars:
            out.append(part)
            return
        for i in range(0, len(part), max_chars):
            out.append(part[i : i + max_chars])

    start = 0
    i = 0
    n = len(units)
    while i < n:
        if units[i] not in ".!?":
            i += 1
            continue
        # Take a run of terminators together ("wait!?") so the split lands
        # after all of them rather than between them.
        end = i
        while end + 1 < n and units[end + 1] in ".!?":
            end += 1

        nxt = units[end + 1] if end + 1 < n else None
        if nxt is None:
            push(units[start : end + 1])
            start = end + 1
            i = end + 1
            continue
        if nxt == " ":
            push(units[start : end + 1])
            start = end + 2
            i = end + 2
            continue
        # Mid-token: a decimal point or an identifier, not a sentence end.
        i = end + 1
    if start < n:
        push(units[start:])

    return out


def split_into_chunks(
    text: str,
    max_chars: int = MAX_CHUNK_CHARS,
    overlap_chars: int = CHUNK_OVERLAP_CHARS,
) -> list[str]:
    """Packs sentences greedily up to maxChars, then starts the next chunk with

    enough trailing sentences to cover overlapChars. The overlap is why a fact
    that straddles a boundary is still retrievable whole.
    """
    if max_chars < 1:
        raise ValueError("maxChars must be at least 1")
    if overlap_chars >= max_chars:
        raise ValueError("overlapChars must be smaller than maxChars")

    normalized = normalize(text)
    if len(normalized) == 0:
        return []

    parts = _sentences(normalized, max_chars)
    chunks: list[str] = []
    current: list[list[str]] = []
    current_length = 0

    def flush() -> None:
        nonlocal current, current_length
        if not current:
            return
        chunks.append(" ".join(_from_units(s) for s in current))
        # Carry the tail of this chunk into the next one, sentence by
        # sentence, until the overlap budget is met.
        carried: list[list[str]] = []
        carried_length = 0
        i = len(current) - 1
        while i >= 0 and carried_length < overlap_chars:
            carried.insert(0, current[i])
            carried_length += len(current[i]) + 1
            i -= 1
        # All of it carrying over would mean no progress, so the last
        # sentence alone is never enough to start a chunk with.
        current = carried if len(carried) < len(current) else []
        current_length = sum(len(s) + 1 for s in current)

    for part in parts:
        if current_length > 0 and current_length + len(part) + 1 > max_chars:
            flush()
            # The carried overlap can be too long to leave room for the
            # sentence that triggered the flush. Dropping it is what keeps
            # the loop moving instead of emitting the same tail twice.
            if current_length > 0 and current_length + len(part) + 1 > max_chars:
                current = []
                current_length = 0
        current.append(part)
        current_length += len(part) + 1
    if current:
        chunks.append(" ".join(_from_units(s) for s in current))

    return chunks


@dataclass(frozen=True)
class Chunk:
    chunk_no: int
    content: str
    content_hash: str


async def chunk_text(
    text: str, max_chars: int = MAX_CHUNK_CHARS, overlap_chars: int = CHUNK_OVERLAP_CHARS
) -> list[Chunk]:
    """Chunks text and hashes each chunk, ready to be compared against what is stored."""
    contents = split_into_chunks(text, max_chars=max_chars, overlap_chars=overlap_chars)
    return [Chunk(index, content, hash_text(content)) for index, content in enumerate(contents)]


def render_invoice(invoice: dict[str, Any]) -> str:
    """One invoice, one chunk of plain prose — a faithful port of renderInvoice.

    Retrieval over the money has to compete with list_invoices, so the
    rendering names the things a person would actually type — the identifier,
    the customer, the status — rather than being a serialized row. Amount
    formatting replicates (amount_cents / 100).toLocaleString("en-US",
    {minimumFractionDigits: 2, maximumFractionDigits: 2}) without floats,
    so it is exact for every integer cent value.
    """
    amount = _format_amount_cents(invoice["amount_cents"])
    if invoice["status"] == "paid" and invoice.get("paid_at"):
        paid = f" It was paid on {invoice['paid_at']}."
    elif invoice["status"] == "paid":
        paid = " It is marked paid with no payment date recorded."
    else:
        paid = ""
    return (
        f"Invoice {invoice['external_id']} for customer {invoice['customer']}. "
        f"Amount {amount} {invoice['currency'].upper()}. "
        f"Status {invoice['status']}. Issued on {invoice['issued_at']}.{paid}"
    )


def _format_amount_cents(amount_cents: int) -> str:
    """en-US integer-and-2-decimal formatting, e.g. 120000 -> "1,200.00"."""
    dollars, cents = divmod(amount_cents, 100)
    return f"{dollars:,}.{cents:02d}"
