"""Signed callback construction (spec 0009, D-19 scheme reuse).

The known-answer vector is generated by the *real* Deno verifier
(supabase/functions/_shared/signature.ts): canonical string + HMAC-SHA256
via Web Crypto. If this test passes, a request signed by this module would
pass checkRequestSignature in the Edge Function for the same secret — the
Python signer is verified against the scheme, not against itself.
"""

from __future__ import annotations

import hashlib
import hmac
import re

import pytest

from modal_transcription import callback

# Generated with the real signature.ts (see py/modal/drafts/hmac-vector.ts).
DENO_VECTOR_SECRET = "test-secret-123"
DENO_VECTOR_TIMESTAMP = 1724200000000
DENO_VECTOR_NONCE = "aBcD_eFgH-1234"
DENO_VECTOR_RAW_BODY = '{"org_id":"00000000-0000-4000-8000-000000000001","audio_hash":"abc123"}'
DENO_VECTOR_HEX = "d54642128363d9d1eaa31ec532530599f91b17e9e62f6e03e8919ba948ed3257"


def test_known_answer_vector_matches_deno_signature_module() -> None:
    """The exact vector the Deno verifier produced must reproduce exactly."""
    canonical = callback.canonical_string(
        DENO_VECTOR_TIMESTAMP, DENO_VECTOR_NONCE, DENO_VECTOR_RAW_BODY
    )
    assert canonical == f"v1:{DENO_VECTOR_TIMESTAMP}:{DENO_VECTOR_NONCE}:{DENO_VECTOR_RAW_BODY}"
    assert (
        callback.sign(
            DENO_VECTOR_SECRET, DENO_VECTOR_TIMESTAMP, DENO_VECTOR_NONCE, DENO_VECTOR_RAW_BODY
        )
        == DENO_VECTOR_HEX
    )


def test_canonical_string_is_exactly_the_shared_scheme() -> None:
    assert callback.canonical_string(1234, "n1", "{}") == "v1:1234:n1:{}"


def test_sign_matches_independent_hmac_implementation() -> None:
    secret = "another-secret"
    ts = 1724200000001
    nonce = "nonce-0001"
    body = '{"a":1}'
    expected = hmac.new(
        secret.encode(),
        f"v1:{ts}:{nonce}:{body}".encode(),
        hashlib.sha256,
    ).hexdigest()
    assert callback.sign(secret, ts, nonce, body) == expected


def test_build_signed_request_headers_shape() -> None:
    payload = {"org_id": "00000000-0000-4000-8000-000000000001", "transcript": {"text": "hi"}}
    req = callback.build_signed_request(
        payload, "secret", timestamp_ms=1724200000000, nonce="aBcD_eFgH-1234"
    )
    assert req["headers"]["x-webhook-timestamp"] == "1724200000000"
    assert req["headers"]["x-webhook-nonce"] == "aBcD_eFgH-1234"
    # 64 lowercase hex chars — what the verifier's HEX_RE demands.
    assert re.fullmatch(r"[0-9a-f]{64}", req["headers"]["x-webhook-signature"])
    assert req["headers"]["content-type"] == "application/json"


def test_build_signed_request_signs_the_exact_body_sent() -> None:
    """The wire body and the signed string must be the same bytes: sending a
    re-serialization would fail the HMAC check on the other side."""
    payload = {"org_id": "00000000-0000-4000-8000-000000000001", "n": 1}
    req = callback.build_signed_request(
        payload, "secret", timestamp_ms=1724200000000, nonce="aBcD_eFgH-1234"
    )
    assert req["raw_body"] in req["canonical"]
    assert req["canonical"] == f"v1:{req['timestamp_ms']}:{req['nonce']}:{req['raw_body']}"
    assert (
        callback.sign("secret", req["timestamp_ms"], req["nonce"], req["raw_body"])
        == req["headers"]["x-webhook-signature"]
    )


def test_different_secret_produces_different_signature() -> None:
    a = callback.build_signed_request({"x": 1}, "secret-a", timestamp_ms=1, nonce="aBcD_eFgH-1234")
    b = callback.build_signed_request({"x": 1}, "secret-b", timestamp_ms=1, nonce="aBcD_eFgH-1234")
    assert a["headers"]["x-webhook-signature"] != b["headers"]["x-webhook-signature"]


def test_default_nonce_and_timestamp_are_accepted_shapes() -> None:
    req = callback.build_signed_request({"x": 1}, "secret")
    assert re.fullmatch(r"[A-Za-z0-9_-]{8,128}", req["nonce"])
    assert req["timestamp_ms"] > 0
    assert req["headers"]["x-webhook-nonce"] == req["nonce"]
    assert req["headers"]["x-webhook-timestamp"] == str(req["timestamp_ms"])


def test_correlation_id_header_when_requested() -> None:
    req = callback.build_signed_request({"x": 1}, "secret", correlation_id="corr-123")
    assert req["headers"]["x-correlation-id"] == "corr-123"


def test_rejects_nonce_the_verifier_would_reject() -> None:
    with pytest.raises(ValueError):
        callback.build_signed_request({"x": 1}, "secret", nonce="short")
    with pytest.raises(ValueError):
        callback.build_signed_request({"x": 1}, "secret", nonce="has spaces!")
